name: frontend
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  emoji_picker_flutter: ^4.3.0

  cached_network_image: ^3.4.1

  firebase_core: ^3.13.0

  firebase_auth: ^5.5.3

  cloud_firestore: ^5.6.7

  firebase_storage: ^12.4.5

  google_sign_in: ^6.3.0

  image_picker: ^1.1.2

  firebase_messaging: ^15.1.6

  googleapis_auth: ^1.6.0

  http: ^1.2.2

  flutter_notification_channel: ^3.1.0

  gallery_saver_plus: ^3.2.1

  lottie: ^3.2.0

  google_generative_ai: ^0.4.3

  intl: ^0.20.1

  gif: ^2.3.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0

flutter_icons:
  android: "ic_launcher"
  ios: true
  min_sdk_android: 28
  image_path: "assets/logo.png"
  remove_alpha_ios: true

#  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
   - assets/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
